var apparatus_common=(function($){var els;var imagesPreloaded=false;var pageLoaded=false;var startTime=new Date().getTime();var preloadInterval;var pageRendered=false;var scrollTop=0;var winW=0;var winH=0;var viewportW=0;var viewportH=0;var scrollbarWidth=0;var prevViewportW=0;var isTouch=Modernizr.touch;var hamburgerAnimated=false;var stockistsScrollPane;var stockistsScrollAPI;var contactScrollPane;var contactScrollAPI;var cartScrollPane;var cartScrollAPI;var navBreakpoint=740;var tabletBreakpoint=1024;var hasScrolled=false;var retina=window.devicePixelRatio>1;function init(){els={$window:$(window),$html:$('html'),$body:$('body'),$hidden:$('.hidden'),$menuToggle:$('.menu-toggle'),$pageWrap:$('.l-page-wrap'),$sidebar:$('.sidebar-menu'),$sidebarStockists:$('.sidebar-stockists'),$overlay:$('.overlay'),$navMenu:$('.nav-menu'),$menuSidebarBottom:$('.sidebar-menu .sidebar-bottom'),$cartToggle:$('.cart-toggle'),$sidebarCart:$('.sidebar-cart'),$cartScroller:$('.sidebar-cart .sidebar-scroller'),$hero:$('.hero'),$heroInner:$('.hero .inner'),$heroParallax:null,$heroParallaxInner:null,$contentWrap:$('.l-content-wrap'),$slideIn:$('.slide-in'),$accordionPanels:$('.accordion > .panel'),$expander:$('.expander')}
var imagesToLoad=[];if(els.$hero[0]){var heroImages=els.$hero.attr('data-img-src').split(',');for(var i=0;i<heroImages.length;i++){imagesToLoad.push(heroImages[i]);};}
$('img').each(function(){imagesToLoad.push($(this).attr('src'));});preloadImages(imagesToLoad,function(){imagesPreloaded=true;});scrollbarWidth=getScrollbarWidth();els.$cartToggle.css({'margin-right':scrollbarWidth});window.setTimeout(function(){$('.logo, .menu-toggle, .cart-toggle').removeClass('fade-on-load').addClass('fade-in');},500);els.$window.load(function(){pageLoaded=true;});preloadInterval=window.setInterval(function(){var time=new Date().getTime();var elapsed=time- startTime;var minTime=0;var timeout=3000;if((elapsed>timeout)||(imagesPreloaded&&pageLoaded&&elapsed>minTime)){window.clearInterval(preloadInterval);hidePageLoader();window.setTimeout(function(){renderPage();},500);}},100);animateLoader();}
function animateLoader(){$('.loader-dot').velocity({scaleX:[1,'ease',0.1],scaleY:[1,'ease',0.1]},{duration:2000,complete:function(){animateLoader();}});}
function showPageLoader(){$('.page-loader').fadeIn(250);}
function hidePageLoader(){$('.page-loader').fadeOut(250);}
function showCartLoader(){$('.sidebar-cart-loader').fadeIn(250);}
function hideCartLoader(){$('.sidebar-cart-loader').fadeOut(250);}
function viewport(){var e=window,a='inner';if(!('innerWidth'in window)){a='client';e=document.documentElement||document.body;}
return{width:e[a+'Width'],height:e[a+'Height']};}
function getScrollbarWidth(){var outer=document.createElement("div");outer.style.visibility="hidden";outer.style.width="100px";outer.style.msOverflowStyle="scrollbar";document.body.appendChild(outer);var widthNoScroll=outer.offsetWidth;outer.style.overflow="scroll";var inner=document.createElement("div");inner.style.width="100%";outer.appendChild(inner);var widthWithScroll=inner.offsetWidth;outer.parentNode.removeChild(outer);return widthNoScroll- widthWithScroll;}
function preloadImages(srcs,callback){var img;var remaining=srcs.length;for(var i=0;i<srcs.length;i++){console.log('preloading img: '+ srcs[i]);img=new Image();img.onload=function(){--remaining;if(remaining<=0){callback();}};img.src=srcs[i];}}
function renderPage(){$('html, body').animate({'scrollTop':0},1);stockistsScrollPane=$('.sidebar-stockists .sidebar-scroller').jScrollPane();stockistsScrollAPI=stockistsScrollPane.data('jsp');contactScrollPane=$('.sidebar-contact .sidebar-scroller').jScrollPane();contactScrollAPI=contactScrollPane.data('jsp');cartScrollPane=$('.sidebar-cart .sidebar-scroller').jScrollPane();cartScrollAPI=cartScrollPane.data('jsp');els.$accordionPanels.hide();$('option[value=""]:not(:contains("Month")):not(:contains("Year"))').text('Select');setupDropkickSelects('select:not(.state_select)');$('select.state_select').dropkick({mobile:true,initialize:function(){var $input,dk=this;$('.dk-selected',dk.data.elem).after(['<div class="dk-search">','<input type="text" class="dk-search-input" placeholder="Search">','</div>',].join(''));$input=$('.dk-search-input',dk.data.elem);$input.on('click',function(event){event.stopPropagation();}).on('keypress keyup',function(event){var found=dk.search(this.value,dk.data.settings.search);event.stopPropagation();$('.dk-option',dk.data.elem).remove();if(found.length){$(found).appendTo(dk.data.elem.lastChild);dk.selectOne(found[0]);}else{$('<li></li>').addClass('dk-option dk-option-disabled').text('Not Found').appendTo(dk.data.elem.lastChild);}
found.length&&dk.selectOne(found[0]);});},open:function(){$('.dk-search-input',this.data.elem).focus();},close:function(){$('.dk-search-input',this.data.elem).val('').blur();$('.dk-option',this.data.elem).remove();$(this.options).appendTo(this.data.elem.lastChild);},change:function(){var data=this.data;$(data.select).trigger('change');}});$('form.checkout :input').removeAttr('placeholder');if(els.$hero[0]){var heroImages=els.$hero.attr('data-img-src').split(',');if(!isTouch){els.$hero.clone().insertBefore(els.$pageWrap).removeClass('hero-static').addClass('hero-parallax');}
els.$heroParallax=$('.hero-parallax');els.$heroParallaxInner=$('.hero-parallax .inner');$('.hero .inner').backstretch(heroImages,{fade:2000,duration:3500});}
if(els.$body.hasClass('woocommerce-checkout')){$('body').bind('checkout_error',function(e){els.$contentWrap.velocity('scroll',{container:els.$pageWrap,duration:1000});});}
$('.infinite-grid').infinitescroll({navSelector:'.pagination',nextSelector:'.pagination a',itemSelector:'.infinite-grid .item',behavior:'local',binder:els.$pageWrap,prefill:false,bufferPx:200,debug:false,loading:{finishedMsg:'No more articles to load.',msgText:"",speed:0,img:'/wp-content/themes/apparatus/img/ajax-loader.gif'}},function(newElements){var $newElems=$(newElements).css({opacity:0});$('.infinite-grid').isotope('appended',$newElems);$newElems.animate({opacity:1},400,function(){scrollHandler();});$newElems.each(function(){var $img=$(this).find('.img');var img=$(this).find('img');$img.css({opacity:0});img.imagesLoaded(function(){$img.animate({opacity:1},400);});});});if($('label[for="payment_method_firstdata"]').length){$('body').bind('updated_checkout',function(e){$('label[for="payment_method_firstdata"]').html($('label[for="payment_method_firstdata"]').html().replace('Credit Card',''));if(!$('.dk-select.woocommerce-cc-month').length){setupDropkickSelects('#firstdata-exp-month, #firstdata-exp-year');}});}
scaleLayout();$('.product-img-lg.default').each(function(){$(this).backstretch($(this).attr('data-src'),{fade:0});});if(!isTouch){$('.product-img-lg:not(.default)').each(function(){$(this).backstretch($(this).attr('data-src'),{fade:0});});}
$('.product-img-lg:not(.default)').hide();if($('.product-carousel').length){$('.product-carousel').carouFredSel({width:'100%',height:'variable',responsive:true,infinite:true,auto:2000,items:{height:'variable'},scroll:{fx:'crossfade',duration:400,pauseOnHover:false}});}
if($('.flexible-content-carousel').length){$('.flexible-content-carousel').carouFredSel({width:'100%',height:'variable',responsive:true,infinite:true,auto:2000,items:{height:'variable'},scroll:{fx:'crossfade',duration:0,pauseOnHover:false}});}
$('.masonry-grid:not(.infinite-grid):not(.finishes-grid)').imagesLoaded(function(){console.log('masonry images loaded');$('.masonry-grid:not(.infinite-grid):not(.finishes-grid)').isotope({itemSelector:'.item',layoutMode:'masonry',masonry:{columnWidth:'.grid-sizer'}});});$('.infinite-grid').isotope({itemSelector:'.item',layoutMode:'masonry',transitionDuration:'0s',masonry:{columnWidth:'.grid-sizer'}});initializeSlideIns();if(retina&&navigator.userAgent.toLowerCase().indexOf('chrome')>-1){$('.parallax-strip').addClass('static');}
setupEventHandlers();if(isTouch||viewport().width<=tabletBreakpoint){finishesMasonryGrid();}else{finishesCarousels();}
$('.fade-on-load').removeClass('fade-on-load').addClass('fade-in');pageRendered=true;}
function setupEventHandlers(){els.$menuToggle.on('click',function(){if(!els.$html.hasClass('menu-open')){openMenu();}else if(els.$html.hasClass('stockists-open')){closeStockists();}else if(els.$html.hasClass('contact-open')){closeContact();}else{closeMenu();}});$('.btn-stockists').on('click',function(e){e.preventDefault();openStockists();});$('.btn-contact').on('click',function(e){e.preventDefault();openContact();});els.$cartToggle.on('click',function(e){e.preventDefault();if(!els.$html.hasClass('cart-open')&&!els.$html.hasClass('menu-open')){openCart();}else{closeCart();}});els.$overlay.on('mousedown touchstart',function(){if(els.$html.hasClass('menu-open')){closeMenu();}else if(els.$html.hasClass('cart-open')){closeCart();}});if(!isTouch){$('.category-names a').on('mouseenter',function(){var category=$(this).attr('data-category');$('.product-img-lg:not(.default)').hide();$('#img-'+ category).show();$('.img-overlay').velocity('stop').css({opacity:1}).velocity({opacity:0},{duration:2000,easing:'easeOutQuart'});});$('.category-names').on('mouseleave',function(){$('.product-img-lg:not(.default)').hide();$('.img-overlay').velocity('stop').css({opacity:1}).velocity({opacity:0},{duration:2000,easing:'easeOutQuart'});});}
$('.finish-draggable').draggable({containment:'window',helper:'clone',appendTo:'body',cursor:'move',scroll:false,start:function(e,ui){$(ui.helper).addClass('ui-draggable-helper');}});$('.finish-droppable .dropzone').droppable({hoverClass:'ui-state-hover',drop:function(event,ui){var $draggable=ui.draggable;var $el=$(this);var $img=$('<div class="img">');$el.addClass('has-img').find('.img').remove();console.log($draggable.find('img').attr('src'));$img.css('background-image','url('+ $draggable.find('img').attr('src')+')');$img.appendTo($el).css({'opacity':0.01}).animate({'opacity':1},500);$(this).parent().find('.title').text($draggable.find('.title').text());}});$('.finish-droppable .dropzone .close').on('click',function(e){e.preventDefault();var $el=$(this);$el.parent().removeClass('has-img').find('.img').fadeOut(500);$el.closest('.finish-droppable').find('.title').html('&nbsp;');});$('.accordion > .panel-label').on('click',function(){var $target=$(this).next();var $accordion=$(this).parent();if($target.hasClass('active')){$accordion.find('.panel.active').addClass('closing').slideUp(500,function(){$accordion.find('.closing').removeClass('active closing');});$accordion.find('.panel-label.active').removeClass('active');}else{$accordion.find('.panel.active').addClass('closing').slideUp(500);$accordion.find('.panel-label.active').removeClass('active');$(this).addClass('active');$target.addClass('active').slideDown(500,function(){$accordion.find('.closing').removeClass('active closing');stockistsScrollAPI.reinitialise();});}});$('.masonry-grid').on('mouseenter','.expander',function(){$(this).addClass('active');});$('.masonry-grid').on('mouseleave','.expander',function(){$(this).removeClass('active');});$('.masonry-grid').on('touchstart','.expander',function(){$(this).toggleClass('active');});$('.nav-dropdown').dropdown({gutter:0,delay:40});$('.nav-dropdown a').on('click',function(){$('.nav-dropdown.active').dropdown('close');});$('.nav-dropdown').siblings('a').on('click',function(){$(this).parent().siblings('li').find('.nav-dropdown.active').dropdown('close');});$('.back-to-top').on('click',function(e){e.preventDefault();var offset=els.$body.hasClass('single-product')&&viewport().width<=navBreakpoint?0- $('.hero-static').outerHeight()- 73:0;var $el;if($('.hero-parallax').length&&$('.hero-parallax').is(':visible')){$el=els.$contentWrap;}else if($('.hero-static').length){$el=$('.hero-static');}else{$el=els.$pageWrap.children(':first');}
$el.velocity('scroll',{container:els.$pageWrap,offset:offset,duration:1000});});$('.scroll-down-arrow').on('click',function(){els.$contentWrap.velocity('scroll',{container:els.$pageWrap,offset:viewportW>navBreakpoint?$('.hero-parallax').outerHeight()+ 10:10,duration:1000});});els.$body.on('click','.btn-continue-shopping',function(e){e.preventDefault();closeCart();});$('.single-add-to-cart-button, .single_add_to_cart_button').on('click',function(e){e.preventDefault();var target=e.target;var dataset=$(e.target).closest('form');var values=dataset.serialize();values=values.replace(/&add-to-cart=([0-9]+)/,'&add-to-cart-val=$1');addToCart(values);});els.$body.on('click','.cart-item .remove',function(e){e.preventDefault();var itemKey=$(this).closest('[data-cart-item-key]').attr('data-cart-item-key');updateCartQty(itemKey,0,null);});els.$body.on('click','.cart-item .btn-qty-up',function(e){var $qtyVal=$(this).siblings('.qty-val');var newQty=parseFloat($qtyVal.text(),10)+ 1;var itemKey=$(this).closest('[data-cart-item-key]').attr('data-cart-item-key');updateCartQty(itemKey,newQty,$qtyVal);});els.$body.on('click','.cart-item .btn-qty-down',function(e){var $qtyVal=$(this).siblings('.qty-val');var newQty=parseFloat($qtyVal.text(),10)- 1;var itemKey=$(this).closest('[data-cart-item-key]').attr('data-cart-item-key');if(newQty>0){updateCartQty(itemKey,newQty,$qtyVal);}});$('a[href="#buy"]').on('click',function(e){e.preventDefault();var offset=$('.single-product-form-wrap').offset().top+ els.$pageWrap.scrollTop();if(viewport().width<=navBreakpoint||isTouch){offset-=isTouch?$('.hero-static').outerHeight()+ 50:$('.hero-static').outerHeight()+ 73;}else{offset-=50;}
els.$contentWrap.velocity('scroll',{container:els.$pageWrap,offset:Math.round(offset),duration:1000});});$('a[href="#product-info"]').on('click',function(e){e.preventDefault();var offset=$('.product-info').offset().top+ els.$pageWrap.scrollTop();if(viewport().width<=navBreakpoint||isTouch){offset-=isTouch?$('.hero-static').outerHeight()+ 50:$('.hero-static').outerHeight()+ 73;}else{offset-=50;}
els.$contentWrap.velocity('scroll',{container:els.$pageWrap,offset:Math.round(offset),duration:1000});});$(window).on('resize',$.throttle(10,function(){scaleLayout();parallax();}));els.$pageWrap.on('scroll',function(){scrollTop=els.$pageWrap.scrollTop();window.requestAnimationFrame(scrollHandler);});}
function scrollHandler(){parallax();if(!hasScrolled){$('.scroll-down-arrow').fadeOut(250);}
if(!isTouch){$('.slide-in').not('.sliding').each(function(i,el){var $el=$(el);if($el.visible(true,null,null,150)){$el.addClass('sliding');$el.velocity({translateZ:0,translateY:[0,'ease',150]},{duration:$el.index()%2===0?800:600,complete:function(){$el.removeClass('slide-in sliding');}});}});}
if($('.parallax-strip').length&&$('.parallax-strip').visible(true)){$('.masonry-grid > li').velocity('stop').removeClass('slide-in sliding').css({'transform':''});}}
function scaleLayout(){viewportW=viewport().width;viewportH=viewport().height;winW=els.$window.width();winH=els.$window.height();if($('.hero').length){if(els.$body.hasClass('home')){var maxH=viewportW;var heroH=Math.min(maxH,viewportH);$('.hero').css({'padding-bottom':heroH});els.$contentWrap.css({'margin-top':heroH});}else{var maxH=viewportH;var heroH=Math.min(maxH,Math.round(viewportW*(1390/2625)));$('.hero').css({'padding-bottom':heroH});els.$contentWrap.css({'margin-top':heroH});}}
if(els.$navMenu.outerHeight()+ els.$navMenu.offset().top+ els.$menuSidebarBottom.outerHeight()>viewportH){els.$menuSidebarBottom.addClass('static');}else if(els.$menuSidebarBottom.hasClass('static')){els.$menuSidebarBottom.removeClass('static');}
stockistsScrollAPI.reinitialise();contactScrollAPI.reinitialise();scaleCart();$('.product-carousel li').css({height:$('.single-product-form-wrap').outerHeight(),width:$('.product-carousel-col').width()});$('.flexible-content-carousel').each(function(){var $el=$(this);var w=$el.closest('.grid-module').width()
var h=w;if($el.hasClass('landscape')){h=w*0.75;}else if($el.hasClass('portrait')){h=w*1.3333;}
$el.find('li').css({height:Math.round(h)});});initializeSlideIns();if(pageRendered){if(prevViewportW<=navBreakpoint&&viewport().width>navBreakpoint){resetHamburgerIcon();}else if(prevViewportW>navBreakpoint&&viewport().width<=navBreakpoint){resetHamburgerIcon();}
if(prevViewportW<=1024&&viewport().width>1024){if($('.finishes-carousel').length){destroyFinishesMasonryGrid();finishesCarousels();}}else if(prevViewportW>1024&&viewport().width<=1024){if($('.finishes-carousel').length){destroyFinishesCarousels();finishesMasonryGrid();}}}
prevViewportW=viewport().width;}
function setupDropkickSelects(selector){$(selector).each(function(){$(this).dropkick({mobile:true,change:function(){var data=this.data;$(data.select).trigger('change');}});});}
function initializeSlideIns(){els.$slideIn.each(function(i,el){var el=$(el);if(el.visible(true,null,null,150)){el.removeClass('slide-in');}});}
function openMenu(){els.$html.addClass('menu-open');window.setTimeout(function(){els.$html.addClass('menu-open-anim');},25);hamburgerAnimated=true;$('.hamburger-bar:nth-child(1)').velocity('stop',true).velocity({top:viewportW>navBreakpoint?30:15},{delay:500,duration:400}).velocity({rotateZ:'45deg'},{duration:400});$('.hamburger-bar:nth-child(2)').velocity('stop',true).velocity({opacity:0,},{delay:900,duration:1});$('.hamburger-bar:nth-child(3)').velocity('stop',true).velocity({top:viewportW>navBreakpoint?30:15},{delay:500,duration:400}).velocity({rotateZ:'-45deg'},{duration:400});}
function closeMenu(){els.$html.removeClass('menu-open stockists-open contact-open').addClass('menu-closing');window.setTimeout(function(){els.$html.removeClass('menu-open-anim');},25);window.setTimeout(function(){els.$html.removeClass('menu-closing');},600);if(hamburgerAnimated){animateArrowBtnBack();$('.hamburger-bar:nth-child(1)').velocity({rotateZ:'0deg'},{delay:500,duration:400}).velocity({top:viewportW>navBreakpoint?24:12},{duration:400});$('.hamburger-bar:nth-child(2)').velocity({opacity:1},{delay:900,duration:1});$('.hamburger-bar:nth-child(3)').velocity({rotateZ:'0deg'},{delay:500,duration:400}).velocity({top:viewportW>navBreakpoint?36:18},{duration:400});}}
function openStockists(){var activePanel=els.$sidebarStockists.find('.accordion .panel.active');els.$sidebarStockists.find('.accordion .active').removeClass('active');activePanel.removeClass('closing').slideUp(1,function(){stockistsScrollAPI.reinitialise();});stockistsScrollAPI.scrollTo(0,0);els.$html.addClass('stockists-open');animateArrowBtnFwd();}
function closeStockists(){els.$html.removeClass('stockists-open');animateArrowBtnBack();}
function openContact(){contactScrollAPI.scrollTo(0,0);els.$html.addClass('contact-open');animateArrowBtnFwd();}
function closeContact(){els.$html.removeClass('contact-open');animateArrowBtnBack();}
function openCart(){els.$html.addClass('cart-open');window.setTimeout(function(){els.$html.addClass('cart-open-anim').removeClass('adding-to-cart');},25);}
function closeCart(){els.$html.removeClass('cart-open').addClass('cart-closing');window.setTimeout(function(){els.$html.removeClass('cart-open-anim');},25);if($('.cart-list .empty').length){window.setTimeout(function(){els.$cartToggle.addClass('u-none');},600);}
window.setTimeout(function(){els.$html.removeClass('cart-closing');},600);}
function addToCart(values){els.$html.addClass('adding-to-cart');showPageLoader();$.ajax({type:'POST',url:window.location.protocol+'//'+ window.location.hostname+'/add-to-cart',data:values,success:function(response,textStatus,jqXHR){updateCart(response);els.$cartToggle.removeClass('u-none');hidePageLoader();openCart();},error:function(jqXHR,textStatus,error){console.log('AJAX add to cart error: '+ textStatus);}});}
function updateCartQty(itemKey,qty,$qtyVal){els.$html.addClass('cart-ajax-in-progress');showCartLoader();$.ajax({type:'POST',data:{'item-key':itemKey,qty:qty},url:window.location.protocol+'//'+ window.location.hostname+'/update-item-quantity',success:function(response,textStatus,jqXHR){console.log('AJAX update cart quantity success');els.$html.removeClass('cart-ajax-in-progress');hideCartLoader();if(els.$body.hasClass('woocommerce-checkout')){if(qty>0){els.$body.trigger('update_checkout');}else{location.reload();}}else{updateCart(response);}},error:function(jqXHR,textStatus,error){console.log('AJAX update cart quantity error: '+ textStatus);els.$html.removeClass('cart-ajax-in-progress');hideCartLoader();}});}
function updateCart(response){els.$sidebarCart.find('.cart-totals').html($(response).find('.cart-totals').html());els.$sidebarCart.find('.cart-buttons').html($(response).find('.cart-buttons').html());cartScrollAPI.getContentPane().html($(response).find('.sidebar-scroller').html());scaleCart();}
function scaleCart(){els.$cartScroller.css({height:viewportH- els.$sidebarCart.find('.cart-buttons').height()}).find('.cart-list').css({'padding-bottom':els.$sidebarCart.find('.cart-totals').outerHeight()});cartScrollAPI.reinitialise();}
function animateArrowBtnFwd(){hamburgerAnimated=true;$('.hamburger-bar:nth-child(1)').velocity({top:viewportW>navBreakpoint?33:17,rotateZ:'40deg',width:viewportW>navBreakpoint?12:7,},{duration:200});$('.hamburger-bar:nth-child(2)').css({opacity:0});$('.hamburger-bar:nth-child(3)').velocity({top:viewportW>navBreakpoint?26:13,rotateZ:'-40deg',width:viewportW>navBreakpoint?12:7,},{duration:200});}
function animateArrowBtnBack(){if(hamburgerAnimated){$('.hamburger-bar:nth-child(1)').velocity('stop',true).velocity({top:viewportW>navBreakpoint?30:15,rotateZ:'45deg',width:viewportW>navBreakpoint?17:9},{duration:200});$('.hamburger-bar:nth-child(2)').velocity('stop',true).css({opacity:0});$('.hamburger-bar:nth-child(3)').velocity('stop',true).velocity({top:viewportW>navBreakpoint?30:15,rotateZ:'-45deg',width:viewportW>navBreakpoint?17:9},{duration:200});}}
function resetHamburgerIcon(){hamburgerAnimated=false;$('.hamburger-bar').css({opacity:'',top:'',transform:'',width:viewportW>navBreakpoint?17:9});}
function parallax(){var $logoLg=$('.site-title');if(!isTouch){if(els.$heroParallaxInner){els.$heroParallaxInner.css({transform:'translate3d(0,'+(0-(scrollTop/2.5))+'px,0)'});}
$logoLg.css({transform:'translate3d(0,'+((scrollTop/2.5)- scrollTop)+'px,0)'});}}
function finishesMasonryGrid(){$('.finish-draggable').draggable('disable');$('.finishes-carousel').isotope({itemSelector:'.item',layoutMode:'masonry'});}
function destroyFinishesMasonryGrid(){$('.finishes-carousel').isotope('destroy');}
function finishesCarousels(){$('.finishes-grid .slide-in').removeClass('slide-in');$('.finish-draggable').draggable('enable');if($('.finishes-carousel').length){$('.finishes-carousel-1 ul').carouFredSel({width:'100%',height:120,responsive:true,infinite:false,circular:false,items:{width:130,height:120,visible:{min:1,max:5}},scroll:{items:1,fx:'scroll',duration:500,pauseOnHover:false,timeoutDuration:10000},auto:{play:false},prev:'.finishes-carousel-1 .prev',next:'.finishes-carousel-1 .next'});$('.finishes-carousel-2 ul').carouFredSel({width:'100%',height:120,responsive:true,infinite:false,circular:false,items:{width:130,height:120,visible:{min:1,max:5}},scroll:{items:1,fx:'scroll',duration:500,pauseOnHover:false,timeoutDuration:10000},auto:{play:false},prev:'.finishes-carousel-2 .prev',next:'.finishes-carousel-2 .next'});}}
function destroyFinishesCarousels(){$('.finishes-carousel ul').trigger('destroy');}
return{init:init,viewport:viewport};}(jQuery));jQuery(document).ready(function($){apparatus_common.init();}(jQuery));